/**
 * OWNER: Dev B (screens) - SOLE OWNER
 *
 * Dev A: do not edit this file. If you need a new route, ask B.
 * This is the file everyone wants to touch, so it breaks most often.
 *
 * TODO(B): wire up the real pages and the RequireAuth guard.
 */
import { createBrowserRouter, Navigate } from 'react-router-dom';

export const router = createBrowserRouter([
  // Public
  // { path: '/login',  element: <LoginPage /> },
  // { path: '/signup', element: <SignupPage /> },

  // Protected (wrap in <RequireAuth>)
  // { path: '/',              element: <HomeDeckPage /> },
  // { path: '/wishlist',      element: <WishlistPage /> },
  // { path: '/apply/:jobId',  element: <ApplyPage /> },
  // { path: '/settings',      element: <SettingsPage /> },

  { path: '*', element: <Navigate to="/" replace /> },
]);
