/**
 * OWNER: Dev B (screens)
 *
 * 개발자 B가 개발자 A를 기다리지 않기 위한 목데이터입니다.
 * A의 useDeck 훅이 준비되기 전까지 이 배열로 스와이프 덱을 끝까지 만드세요.
 *
 * 통합할 때:
 *   const jobs = MOCK_JOBS;        →   const { jobs } = useDeck();
 * import 한 줄만 바꾸면 됩니다.
 *
 * 통합이 끝나면 이 파일을 삭제하세요.
 */
import type { Job } from '@/types';

export const MOCK_JOBS: Job[] = [
  {
    id: 'mock-1',
    storeName: '메가커피 안암역점',
    category: '카페',
    hourlyWage: 12000,
    summary: '음료 제조와 홀 정리를 맡아요. 커피 경험 없어도 괜찮아요.',
    description: '안암역 3번 출구 바로 앞 매장입니다.\n\n음료 제조는 2주간 교육해 드립니다.',
    address: '서울 성북구 안암로 145',
    workDays: '월·수·금',
    workHours: '13:00 ~ 18:00',
    benefits: ['음료제공', '주휴수당', '초보가능'],
    rating: 4.5,
    reviewCount: 3,
    imageUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=600',
  },
  {
    id: 'mock-2',
    storeName: '김밥천국 고려대점',
    category: '음식점',
    hourlyWage: 11500,
    summary: '홀 서빙과 간단한 주방 보조를 함께 합니다.',
    description: '점심 피크타임 위주로 일하실 분을 찾습니다.',
    address: '서울 성북구 고려대로 73',
    workDays: '화·목·토',
    workHours: '11:00 ~ 15:00',
    benefits: ['식사제공', '4대보험', '주휴수당'],
    rating: 4.2,
    reviewCount: 2,
    imageUrl: 'https://images.unsplash.com/photo-1580651315530-69c8e0026377?w=600',
  },
  {
    id: 'mock-3',
    storeName: 'CU 제기동역점',
    category: '편의점',
    hourlyWage: 10500,
    summary: '야간 근무입니다. 손님이 적어 여유로운 편이에요.',
    description: '새벽 시간대는 손님이 거의 없어 개인 공부를 하실 수 있습니다.',
    address: '서울 동대문구 왕산로 지하 111',
    workDays: '금·토·일',
    workHours: '00:00 ~ 06:00',
    benefits: ['야간수당', '주휴수당', '초보가능'],
    rating: 4.0,
    reviewCount: 2,
    imageUrl: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=600',
  },
  {
    id: 'mock-4',
    storeName: '올리브영 성신여대점',
    category: '판매',
    hourlyWage: 11000,
    summary: '상품 진열과 고객 응대를 담당합니다.',
    description: '화장품에 관심 있는 분이면 더 재미있게 일하실 수 있어요.',
    address: '서울 성북구 동소문로 20길 37',
    workDays: '월·화·수',
    workHours: '14:00 ~ 20:00',
    benefits: ['직원할인', '4대보험', '유니폼제공'],
    rating: 4.3,
    reviewCount: 4,
    imageUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600',
  },
  {
    id: 'mock-5',
    storeName: '쿠팡 물류센터 동대문',
    category: '물류',
    hourlyWage: 13500,
    summary: '상품 분류 작업입니다. 단기 하루만도 가능해요.',
    description: '하루 단위로 지원할 수 있습니다. 작업복과 장갑은 제공됩니다.',
    address: '서울 동대문구 천호대로 145',
    workDays: '토·일',
    workHours: '09:00 ~ 18:00',
    benefits: ['식사제공', '단기가능', '당일지급'],
    rating: 3.8,
    reviewCount: 6,
    imageUrl: 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=600',
  },
  {
    id: 'mock-6',
    storeName: '이디야커피 종암점',
    category: '카페',
    hourlyWage: 10800,
    summary: '오전 오픈 담당입니다. 조용한 편이에요.',
    description: '오픈 준비와 오전 음료 제조를 맡습니다. 손님이 많지 않아 여유롭습니다.',
    address: '서울 성북구 종암로 45',
    workDays: '월·수·금',
    workHours: '07:00 ~ 11:00',
    benefits: ['음료제공', '주휴수당'],
    rating: 4.1,
    reviewCount: 2,
    imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=600',
  },
  {
    id: 'mock-7',
    storeName: '한솥도시락 안암점',
    category: '주방',
    hourlyWage: 11200,
    summary: '도시락 포장과 간단한 조리 보조입니다.',
    description: '점심과 저녁 피크타임에 바쁩니다. 조리 경험은 필요 없습니다.',
    address: '서울 성북구 개운사길 12',
    workDays: '화·목·금',
    workHours: '11:30 ~ 14:30',
    benefits: ['식사제공', '초보가능'],
    rating: 4.4,
    reviewCount: 3,
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600',
  },
  {
    id: 'mock-8',
    storeName: '스터디카페 안암점',
    category: '사무',
    hourlyWage: 10400,
    summary: '카운터 응대와 좌석 관리. 앉아서 하는 일이 많아요.',
    description: '이용권 판매, 좌석 배정, 간단한 청소를 담당합니다.\n\n대부분의 시간은 조용합니다.',
    address: '서울 성북구 안암로 9길 22',
    workDays: '토·일',
    workHours: '13:00 ~ 21:00',
    benefits: ['주휴수당', '초보가능', '자유복장'],
    rating: 4.6,
    reviewCount: 5,
    imageUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600',
  },
];
